# Generated by Django 2.1.10 on 2019-09-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0002_contactform_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='exterior',
            field=models.CharField(blank=True, choices=[('vinyl', 'vinyl'), ('wood', 'wood'), ('brick', 'brick'), ('aluminum', 'aluminum'), ('other', 'other')], default=None, max_length=24, null=True),
        ),
    ]
