# Generated by Django 2.1.10 on 2019-09-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0003_contactform_exterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='service_house_wash',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
