# Generated by Django 2.1.10 on 2019-09-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0007_auto_20190924_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='type_of_exterior',
            field=models.CharField(choices=[('Not specified', 'Select'), ('Vinyl', 'Vinyl'), ('Wood', 'Wood'), ('Brick', 'Brick'), ('Aluminum', 'Aluminum'), ('Other', 'Other')], default='Not specified', max_length=24, null=True),
        ),
    ]
