# Generated by Django 2.1.11 on 2020-01-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0025_auto_20191002_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='square_footage',
            field=models.CharField(blank=True, default=None, null=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
