# Generated by Django 2.1.10 on 2019-09-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimages',
            name='After_Picture_Rotation',
            field=models.IntegerField(choices=[(0, '0 degrees'), (90, '90 degrees (clockwise)'), (180, '180 degrees (upside-down)'), (270, '270 degrees (counter-clockwise)')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimages',
            name='Before_Picture_Rotation',
            field=models.IntegerField(choices=[(0, '0 degrees'), (90, '90 degrees (clockwise)'), (180, '180 degrees (upside-down)'), (270, '270 degrees (counter-clockwise)')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='Category',
            field=models.CharField(choices=[('No_Category', 'Select a Category'), ('House_Wash', 'House Wash'), ('Wood_Restoring', 'Wood Restoring'), ('Oxidation_Removal', 'Oxidation Removal'), ('Stain_Removal', 'Stain Removal')], default='No_Category', max_length=64, null=True),
        ),
    ]
