# Generated by Django 2.1.10 on 2019-09-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_images', '0002_auto_20190923_1639'),
        ('uploaded_images', '0002_auto_20190923_1737'),
    ]

    operations = [
    ]
