# Generated by Django 2.1.10 on 2019-09-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_images', '0003_merge_20190923_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimages',
            name='After_Picture_Rotation',
            field=models.IntegerField(choices=[(0, '0 degrees'), (270, '90 degrees (90 degrees clockwise)'), (180, '180 degrees (upside-down)'), (90, '270 degrees (90 degrees counter-clockwise)')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='Before_Picture_Rotation',
            field=models.IntegerField(choices=[(0, '0 degrees'), (270, '90 degrees (90 degrees clockwise)'), (180, '180 degrees (upside-down)'), (90, '270 degrees (90 degrees counter-clockwise)')], default=0, null=True),
        ),
    ]
